name: Push-to-EC2 instance
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_VARIABLE }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            cd cicd-test-server
            # Load NVM properly
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
            eval "$(ssh-agent -s)"
            echo "${{ secrets.SSH_PASS }}" | ssh-add /home/ubuntu/.ssh/id_ed25519
            git stash
            git pull
            ls
            # Start or restart app with PM2 here
            pm2 delete nextjs-3000 || true
            pm2 start npm --name "nextjs-3000" -- start
            pm2 save
