name: Push-to-EC2 instance
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_VARIABLE }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            cd cicd-test-server
            eval "$(ssh-agent -s)"
            echo "${{ secrets.SSH_PASS }}" | ssh-add /home/ubuntu/.ssh/id_ed25519
            git pull
            ls
            npm install
            npm run start
